### PR TITLE
compatible with monolog 1.23.0

### PR DESCRIPTION
**Pull request by joancmp**
See https://github.com/Seldaek/monolog/blob/1.23.0/src/Monolog/Formatter/NormalizerFormatter.php line 116

### CODE REVIEW

**Comment by hmoragregaCMP** [comment]
Scrutinizer has not run tests ??

**Comment by joancmp** [comment]
It says tests passed

**Comment by joancmp** [comment]
i ran the tests in local and all passed

**Comment by joancmp** [comment]
added tests, fixed scrutinizer

**Pull request merged**
